SELECT CAR_ID, CAR_TYPE, FEE FROM(
SELECT E.CAR_ID, ROUND((E.DAILY_FEE*(100-F.DISCOUNT_RATE)/100)*30) AS FEE, F.CAR_TYPE FROM
(SELECT A.CAR_ID, B.DAILY_FEE, B.CAR_TYPE FROM
(SELECT CAR_ID, MIN(START_DATE) AS STARTDATE, MAX(END_DATE) AS ENDDATE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID) A
INNER JOIN CAR_RENTAL_COMPANY_CAR B
ON A.CAR_ID = B.CAR_ID
WHERE (CAR_TYPE='SUV' OR CAR_TYPE='세단') AND (STARTDATE>'2022-11-30' OR ENDDATE<'2022-11-01')) E
INNER JOIN
(SELECT CAR_TYPE,DISCOUNT_RATE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
WHERE (CAR_TYPE='세단' OR CAR_TYPE='SUV') AND DURATION_TYPE LIKE '30%') F
ON E.CAR_TYPE = F.CAR_TYPE) G
WHERE FEE>=500000 AND FEE<2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID

