-- 코드를 작성해주세요
SELECT ID, (CASE WHEN RK/(SELECT COUNT(*) FROM ECOLI_DATA)*100<=25 THEN 'CRITICAL'
                 WHEN RK/(SELECT COUNT(*) FROM ECOLI_DATA)*100<=50 THEN 'HIGH'
                 WHEN RK/(SELECT COUNT(*) FROM ECOLI_DATA)*100<=75 THEN 'MEDIUM' ELSE 'LOW' END) AS COLONY_NAME FROM(
SELECT ID,SIZE_OF_COLONY,RANK()OVER(ORDER BY SIZE_OF_COLONY DESC) AS RK
FROM ECOLI_DATA) B
ORDER BY ID