WITH U AS(
    SELECT USER_ID 
    FROM USER_INFO
    WHERE JOINED LIKE '2021%'
)
SELECT YEAR,MONTH, COUNT(DISTINCT USER_ID) AS PURCHASED_USERS, ROUND(COUNT(DISTINCT USER_ID)/(SELECT COUNT(*)FROM U),1) AS PUCHASED_RATIO FROM(
SELECT USER_ID,YEAR(SALES_DATE) AS 'YEAR',MONTH(SALES_DATE) AS 'MONTH' FROM ONLINE_SALE WHERE USER_ID IN (SELECT USER_ID FROM U)) B
GROUP BY YEAR,MONTH
ORDER BY YEAR, MONTH