-- 코드를 입력하세요
SELECT FLAVOR FROM(
(SELECT A.FLAVOR, (A.TOTAL_ORDER + B.ST) AS TSUM
FROM FIRST_HALF A
INNER JOIN(
SELECT FLAVOR, SUM(TOTAL_ORDER) AS ST
FROM JULY
GROUP BY FLAVOR) B
ON A.FLAVOR = B.FLAVOR)) C
ORDER BY TSUM DESC
LIMIT 3
