-- 코드를 입력하세요
SELECT E.APNT_NO,D.PT_NAME,E.PT_NO,E.MCDP_CD,E.DR_NAME,E.APNT_YMD
FROM
(SELECT B.APNT_NO,B.PT_NO,B.MCDP_CD,C.DR_NAME, B.APNT_YMD
FROM APPOINTMENT B
INNER JOIN DOCTOR C
ON B.MDDR_ID=C.DR_ID
WHERE B.MCDP_CD='CS' AND APNT_YMD LIKE ('2022-04-13%') AND B.APNT_CNCL_YN ='N') E
INNER JOIN PATIENT D
ON E.PT_NO=D.PT_NO
ORDER BY APNT_YMD